In [4]:
from numpy import *

In [5]:
a = array([2,3,4])

In [6]:
print(a)
a

[2 3 4]


array([2, 3, 4])

In [7]:
a.ndim

1

In [8]:
a.shape

(3,)

In [16]:
b= array([(2,3,4),(5,6,7)])

In [17]:
print(b)
b

[[2 3 4]
 [5 6 7]]


array([[2, 3, 4],
       [5, 6, 7]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [20]:
arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
z = zeros((3,2))

In [24]:
print(z)
z

[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])